# Generated by Django 4.0.3 on 2022-03-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('sobrenome', models.CharField(max_length=25)),
                ('idade', models.IntegerField(max_length=3)),
                ('data_nasc', models.DateField()),
                ('email_cliente', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=15)),
                ('observacao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
